# Autogenerated by devscripts/update-version.py

__version__ = '0.1.3'

RELEASE_GIT_HEAD = '997fa140840a08df3938b40da470c78049fef1f6'

VARIANT = None

UPDATE_HINT = 'This is leohux/media-agent. Do not auto-update from the upstream downloader; it would overwrite the agent layer.'

CHANNEL = 'stable'

ORIGIN = 'leohux/media-agent'

_pkg_version = '0.1.3'
